changelog:
  exclude:
    labels:
      - "release:ignore"
    authors:
      - dependabot
      - dependabot[bot]
      - allcontributors
      - allcontributors[bot]
  categories:
    - title: ":boom: Breaking changes"
      labels:
        - "release:major"
    - title: New Features
      labels:
        - "release:minor"
        - enhancement
    - title: Colors and icons
      labels:
        - file support
    - title: Fixes
      labels:
        - "release:patch"
        - bug
    - title: Packaging, building, and distribution
      labels:
        - packaging
    - title: Other Changes
      labels:
        - "*"
